[lint]
extend-select = ["B", "C4", "I", "N", "Q"]
select = ["E", "F", "W"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["uummannaq_ice"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
